"""Post-processing v2: the design, the fit, and the evaluation protocol.

``tests/test_postprocess.py`` owns the FEATURES — the corridor geometry,
the catalogue, the transform of each stored column. This file owns
everything downstream of them: which columns the design is made of, how
the model is fitted, and how a candidate is scored against a baseline.

The first two tests are the ones that matter most. The v1 design and the
v1 fit are what is in service, and every addition here is supposed to be
*additive*: a run that asks for nothing new must produce the same design
matrix and the same coefficients it produced before any of this existed.
They are pinned against ``fixtures/postprocess_v1_golden.json``, which
was generated by running the pre-v2 module over the same fixtures — so
the comparison is with the code that shipped, not with a restatement of
it.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import numpy as np
import pytest

from dmi_nowcast_core import postprocess as pp
from dmi_nowcast_core.calibrate import IsotonicCalibrator
from tests.golden_fixture import (
    GOLDEN_DESIGN_LEADS,
    GOLDEN_LEADS,
    golden_dataset,
    golden_row,
)

#: The leads the golden pin and the evaluation tests use.
LEADS = GOLDEN_LEADS

#: The v1 design and the v1 fit, as the PRE-v2 module produced them on
#: ``tests/golden_fixture.py``'s rows. Regenerating it is a deliberate
#: act: it means the model in service has been changed on purpose.
GOLDEN = json.loads(
    (Path(__file__).parent / "fixtures" / "postprocess_v1_golden.json").read_text()
)


def _one_row() -> dict:
    return golden_row()


def _golden_features() -> dict:
    """The golden dataset's rows with ``season`` / ``hour_utc`` derived."""
    data = golden_dataset()
    features = dict(data["features"])
    features["season"] = pp.seasons_from_epoch(data["t"])
    features["hour_utc"] = pp.hours_from_epoch(data["t"]).astype(np.float64)
    # ``features`` LAST: ``data`` carries a key of that name too, and the
    # one this returns has to be the augmented copy.
    return {**data, "features": features}


# ---------------------------------------------------------------------------
# v1 is unchanged
# ---------------------------------------------------------------------------


def test_the_v1_design_matrix_is_bit_for_bit_what_it_was() -> None:
    """Same names, same order, same numbers as the shipped module.

    ``spec=None`` — which is what every caller written before the design
    spec passes — has to keep meaning exactly the columns that shipped.
    ``assert_array_equal`` rather than ``approx`` because a NaN in the
    design is a value here: "this run never wrote that column" has to
    land in the same place it always did.
    """
    leads = tuple(GOLDEN["design_leads_one_row"])
    assert leads == GOLDEN_DESIGN_LEADS
    assert list(pp.design_columns(leads)) == GOLDEN["columns"]
    design = pp.build_design(_one_row(), leads)
    assert design.shape == (1, len(GOLDEN["columns"]))
    np.testing.assert_array_equal(design[0], np.array(GOLDEN["one_row"]))


def test_an_empty_spec_is_the_v1_design() -> None:
    """``--design v1`` is a control arm, not a re-implementation of one."""
    leads = GOLDEN_DESIGN_LEADS
    spec = pp.design_spec(None, leads, version=pp.DESIGN_V1)
    assert spec == pp.DesignSpec()
    assert list(pp.design_columns(leads, spec)) == GOLDEN["columns"]
    with_spec = pp.build_design(_one_row(), leads, spec)
    without = pp.build_design(_one_row(), leads)
    np.testing.assert_array_equal(with_spec, without)


def test_the_v1_fit_reproduces_the_shipped_coefficients() -> None:
    """Every coefficient, the standardiser and the predictions, to 1e-9."""
    golden = _golden_features()
    model = pp.fit_postprocess(
        golden["features"], golden["truth"], list(LEADS),
        l2=1.0, design_leads=list(LEADS),
    )
    assert model.kind == pp.KIND_LOGISTIC
    assert model.spec == pp.DesignSpec()
    assert list(model.standardiser.mean) == pytest.approx(
        GOLDEN["scaling_mean"], abs=1e-9,
    )
    assert list(model.standardiser.scale) == pytest.approx(
        GOLDEN["scaling_scale"], abs=1e-9,
    )
    for lead, expected in GOLDEN["fit"].items():
        fitted = model.models[int(lead)]
        assert fitted.intercept == pytest.approx(expected["intercept"], abs=1e-9)
        assert list(fitted.coefficients) == pytest.approx(
            expected["coefficients"], abs=1e-9,
        )
        assert list(fitted.isotonic.raw_breakpoints)[:5] == pytest.approx(
            expected["isotonic_breakpoints"], abs=1e-9,
        )
        assert fitted.n == expected["n"]
        assert fitted.station_offsets == {}
        assert fitted.isotonic_by_season == {}
    predicted = model.predict(golden["features"], 20)[:8]
    assert list(predicted) == pytest.approx(GOLDEN["predict_20_head"], abs=1e-9)


def test_the_default_settings_are_the_model_in_service() -> None:
    """The one test that keeps every new knob off until someone turns it on."""
    settings = pp.FitSettings()
    assert settings.kind == pp.KIND_LOGISTIC
    assert settings.design == pp.DESIGN_V1
    assert settings.isotonic == pp.ISOTONIC_POOLED
    assert settings.station_offsets is False
    assert settings.shared_lead is False
    assert settings.drop_families == ()
    assert settings.l2 == 1.0


def test_a_document_written_before_kind_existed_loads_as_a_logistic() -> None:
    """The deploy-skew direction that matters: old file, new build."""
    golden = _golden_features()
    model = pp.fit_postprocess(
        golden["features"], golden["truth"], list(LEADS),
        design_leads=list(LEADS),
    )
    payload = model.to_json()
    del payload["kind"]
    del payload["design"]
    restored = pp.PostprocessModel.from_json(payload)
    assert restored.kind == pp.KIND_LOGISTIC
    assert restored.spec == pp.DesignSpec()
    assert restored.predict(golden["features"], 20) == pytest.approx(
        model.predict(golden["features"], 20), abs=0.0,
    )


# ---------------------------------------------------------------------------
# The v2 design
# ---------------------------------------------------------------------------


def test_v2_takes_its_extra_columns_from_the_catalogue_at_run_time() -> None:
    """A column the replay grows must reach the design without an edit here.

    The feature side of this module appends to the catalogue; the model
    side is not allowed to carry a second copy of those names. So the
    check is behavioural: invent a column, and it appears.
    """
    catalogue = pp.feature_columns((20,))
    spec = pp.design_spec(None, (20,), version=pp.DESIGN_V2)
    names = {name for name, _definition in catalogue}
    # Everything the v1 design does not already read, and nothing else.
    assert set(spec.extra_columns) <= names
    assert "raw_frac_20" not in spec.extra_columns
    assert "bulk_kmh" not in spec.extra_columns


def test_an_invented_catalogue_column_reaches_the_design(monkeypatch) -> None:
    def catalogue(leads):
        return pp.feature_columns.__wrapped__(leads) if hasattr(
            pp.feature_columns, "__wrapped__",
        ) else (("brand_new_score", "invented by a test"),)

    monkeypatch.setattr(pp, "feature_columns", catalogue)
    spec = pp.design_spec(None, (20,), version=pp.DESIGN_V2)
    assert "brand_new_score" in spec.extra_columns
    names = pp.design_columns((20,), spec)
    assert "brand_new_score" in names
    row = {"brand_new_score": np.array([2.5]), **_one_row()}
    design = pp.build_design(row, (20,), spec)
    assert design[0, list(names).index("brand_new_score")] == 2.5


class TestTheLog1pDecision:
    """Which extra columns are rates, decided from the values, then stored.

    The catalogue holds rain rates whose names do not say so
    (``ens_mean_20``, ``up_max_b0``), so a name rule alone would quietly
    undo in v2 the one transform the v1 design was careful to apply.
    """

    def test_a_name_that_says_it_is_a_rate_is_enough(self) -> None:
        assert pp.wants_log1p("up_mean_40km_mm_h")
        assert pp.wants_log1p("station_radar_km")
        assert not pp.wants_log1p("g_dry_60")

    def test_a_heavy_tailed_non_negative_column_is_caught_by_its_values(self) -> None:
        rng = np.random.default_rng(2)
        rate = np.where(
            rng.uniform(size=4000) < 0.7, 0.0, np.exp(rng.normal(0.5, 1.2, 4000)),
        )
        assert pp.wants_log1p("ens_mean_20", rate)

    def test_a_fraction_a_count_and_a_signed_column_are_left_alone(self) -> None:
        rng = np.random.default_rng(3)
        assert not pp.wants_log1p("share", rng.uniform(0.0, 1.0, 4000))
        assert not pp.wants_log1p("minutes", rng.uniform(0.0, 360.0, 4000))
        assert not pp.wants_log1p("anomaly", rng.normal(size=4000))

    def test_the_decision_is_stored_and_replayed_not_re_derived(self) -> None:
        rng = np.random.default_rng(12)
        rows = _rows_with_motion(4000)
        rows["ens_mean_20"] = np.where(
            rng.uniform(size=4000) < 0.7, 0.0, np.exp(rng.normal(0.5, 1.2, 4000)),
        )
        spec = pp.design_spec(rows, (20,), version=pp.DESIGN_V2)
        assert "ens_mean_20" in spec.log_columns
        names = pp.design_columns((20,), spec)
        assert "log1p_ens_mean_20" in names
        design = pp.build_design(rows, (20,), spec)
        column = design[:, list(names).index("log1p_ens_mean_20")]
        assert column == pytest.approx(np.log1p(rows["ens_mean_20"]))
        # A different set of rows does NOT change the transform: the spec
        # carries the decision, and a serving path replays it.
        other = _rows_with_motion(400, seed=9)
        other["ens_mean_20"] = np.zeros(400)
        replayed = pp.build_design(other, (20,), spec)
        column = replayed[:, list(names).index("log1p_ens_mean_20")]
        assert column.tolist() == [0.0] * 400


def test_a_catalogue_column_the_rows_lack_is_imputed_not_an_error() -> None:
    """One model has to score a tree of old and new partitions."""
    spec = pp.design_spec(None, (20,), version=pp.DESIGN_V2)
    names = pp.design_columns((20,), spec)
    design = pp.build_design(_one_row(), (20,), spec)
    assert design.shape == (1, len(names))
    first = spec.extra_columns[0]
    missing = names.index(
        pp._extra_design_name(first, first in spec.log_columns),
    )
    assert math.isnan(design[0, missing])


class TestSplines:
    """The natural cubic spline basis, from ESL §5.2.1."""

    def test_the_basis_has_two_fewer_columns_than_knots(self) -> None:
        x = np.linspace(0.0, 10.0, 100)
        basis = pp.natural_spline_basis(x, (0.0, 2.5, 5.0, 7.5, 10.0))
        assert basis.shape == (100, 3)

    def test_it_is_linear_outside_the_boundary_knots(self) -> None:
        """That is what makes it *natural* — no cubic blow-up in the tails."""
        knots = (1.0, 2.0, 3.0, 4.0, 5.0)
        x = np.array([6.0, 7.0, 8.0, 9.0])
        basis = pp.natural_spline_basis(x, knots)
        # A linear function has a constant second difference of zero.
        second = np.diff(basis, n=2, axis=0)
        assert np.allclose(second, 0.0, atol=1e-9)

    def test_it_is_not_linear_between_them(self) -> None:
        knots = (0.0, 1.0, 2.0, 3.0, 4.0)
        x = np.linspace(0.0, 4.0, 40)
        basis = pp.natural_spline_basis(x, knots)
        assert np.abs(np.diff(basis[:, 0], n=2)).max() > 1e-6

    def test_a_missing_value_stays_missing(self) -> None:
        basis = pp.natural_spline_basis(
            np.array([1.0, np.nan]), (0.0, 1.0, 2.0, 3.0, 4.0),
        )
        assert np.isfinite(basis[0]).all()
        assert np.isnan(basis[1]).all()

    def test_the_knots_are_training_quantiles_and_are_stored(self) -> None:
        values = np.concatenate([np.linspace(0, 1, 500), np.linspace(1, 20, 500)])
        knots = pp.spline_knots(values)
        assert len(knots) == 5
        assert list(knots) == sorted(knots)
        assert knots[0] == pytest.approx(float(np.quantile(values, 0.05)))
        assert knots[-1] == pytest.approx(float(np.quantile(values, 0.95)))

    def test_a_column_that_cannot_carry_one_gets_none(self) -> None:
        assert pp.spline_knots(np.full(500, np.nan)) == ()
        assert pp.spline_knots(np.ones(500)) == ()
        assert pp.spline_knots(np.linspace(0, 1, 10)) == ()

    def test_the_spec_stores_the_knots_and_the_design_replays_them(self) -> None:
        rows = _rows_with_motion(400)
        spec = pp.design_spec(rows, (20,), version=pp.DESIGN_V2)
        stored = dict(spec.splines)
        assert "bulk_kmh" in stored
        names = pp.design_columns((20,), spec)
        assert "bulk_kmh_ns1" in names
        base = list(names).index("bulk_kmh")
        first = list(names).index("bulk_kmh_ns1")
        design = pp.build_design(rows, (20,), spec)
        expected = pp.natural_spline_basis(
            design[:, base], stored["bulk_kmh"],
        )
        assert design[:, first] == pytest.approx(expected[:, 0], abs=1e-12)


def _rows_with_motion(n: int, seed: int = 1) -> dict:
    rng = np.random.default_rng(seed)
    row = _one_row()
    out = {key: np.repeat(value, n) for key, value in row.items()}
    out["bulk_kmh"] = rng.uniform(1.0, 80.0, size=n)
    out["up_dist_km"] = rng.uniform(0.0, 40.0, size=n)
    out["raw_frac_20"] = rng.uniform(0.0, 1.0, size=n)
    out["season"] = np.array(
        ["summer", "winter", "shoulder"] * (n // 3 + 1), dtype="<U8",
    )[:n]
    return out


def test_the_v2_interactions_are_the_product_of_their_parents() -> None:
    rows = _rows_with_motion(300)
    spec = pp.design_spec(rows, (20,), version=pp.DESIGN_V2)
    names = list(pp.design_columns((20,), spec))
    design = pp.build_design(rows, (20,), spec)
    for a, b in spec.interactions[:4]:
        column = names.index(f"{a}_x_{b}")
        expected = design[:, names.index(a)] * design[:, names.index(b)]
        assert design[:, column] == pytest.approx(expected, abs=1e-12)


def test_v2_carries_the_interactions_the_plan_asked_for() -> None:
    spec = pp.design_spec(None, (20, 30), version=pp.DESIGN_V2)
    pairs = set(spec.interactions)
    assert ("up_no_echo", "bulk_kmh") in pairs
    assert ("raw_frac_20", "season_summer") in pairs
    assert ("raw_frac_30", "season_winter") in pairs
    assert ("hour_sin", "season_summer") in pairs
    assert ("hour_cos", "season_shoulder") in pairs


def test_the_spec_round_trips_through_json() -> None:
    rows = _rows_with_motion(300)
    spec = pp.design_spec(rows, (20,), version=pp.DESIGN_V2, shared_lead=True)
    restored = pp.DesignSpec.from_json(spec.to_json())
    assert restored == spec
    names = pp.design_columns((20,), restored)
    assert names[-2:] == pp.LEAD_COLUMNS
    assert "raw_frac_own" in names


# ---------------------------------------------------------------------------
# Learned station offsets
# ---------------------------------------------------------------------------


def _station_shifted(n_per: int = 1200, seed: int = 4) -> dict:
    """Three stations, one of which is simply wetter than the others.

    Nothing in the design can explain the difference — the predictors are
    drawn identically at all three — so the only place the model can put
    it is a per-station intercept.
    """
    rng = np.random.default_rng(seed)
    stations = np.repeat(np.array(["A", "B", "C"]), n_per)
    n = stations.size
    predictor = rng.normal(size=n)
    shift = np.where(stations == "C", 1.5, 0.0)
    probability = 1.0 / (1.0 + np.exp(-(-1.0 + 0.8 * predictor + shift)))
    y = (rng.uniform(size=n) < probability).astype(np.float64)
    features = {
        "raw_frac_20": 1.0 / (1.0 + np.exp(-predictor)),
        "season": np.array(["summer"] * n, dtype="<U8"),
        "hour_utc": np.full(n, 12.0),
        "station_id": stations,
    }
    return {"features": features, "y": y, "stations": stations, "n": n}


def test_the_offsets_find_the_station_that_is_simply_wetter() -> None:
    data = _station_shifted()
    model = pp.fit_postprocess(
        data["features"], {20: (data["y"], np.ones(data["n"], dtype=bool))},
        [20], design_leads=[20],
        settings=pp.FitSettings(station_offsets=True, l2=1.0),
    )
    offsets = model.models[20].station_offsets
    assert set(offsets) == {"A", "B", "C"}
    assert offsets["C"] > offsets["A"]
    assert offsets["C"] > offsets["B"]
    assert offsets["C"] > 0.3


def test_a_stronger_ridge_on_the_offsets_shrinks_them() -> None:
    data = _station_shifted()
    truth = {20: (data["y"], np.ones(data["n"], dtype=bool))}

    def fit(multiple: float) -> float:
        model = pp.fit_postprocess(
            data["features"], truth, [20], design_leads=[20],
            settings=pp.FitSettings(
                station_offsets=True, l2=1.0, station_l2_multiple=multiple,
            ),
        )
        return model.models[20].station_offsets["C"]

    assert fit(1000.0) < fit(10.0) < fit(0.1)


def test_a_point_the_model_never_saw_gets_no_offset() -> None:
    """A subscriber's coordinate is not a gauge, and must not borrow one."""
    data = _station_shifted()
    model = pp.fit_postprocess(
        data["features"], {20: (data["y"], np.ones(data["n"], dtype=bool))},
        [20], design_leads=[20], settings=pp.FitSettings(station_offsets=True),
    )
    lead = model.models[20]
    design = model.design({k: v for k, v in data["features"].items()})
    home = lead.offsets_for(np.array(["not-a-station"] * design.shape[0]))
    assert np.asarray(home).tolist() == [0.0] * design.shape[0]
    # And with no station column at all, the score is the plain logistic.
    assert lead.offsets_for(None) == 0.0


def test_the_offsets_survive_the_json_round_trip() -> None:
    data = _station_shifted()
    model = pp.fit_postprocess(
        data["features"], {20: (data["y"], np.ones(data["n"], dtype=bool))},
        [20], design_leads=[20], settings=pp.FitSettings(station_offsets=True),
    )
    restored = pp.PostprocessModel.loads(model.dumps())
    assert restored.models[20].station_offsets == pytest.approx(
        model.models[20].station_offsets,
    )
    assert restored.predict(data["features"], 20) == pytest.approx(
        model.predict(data["features"], 20), abs=1e-12,
    )


def test_a_fit_without_offsets_writes_no_offset_block() -> None:
    data = _station_shifted()
    model = pp.fit_postprocess(
        data["features"], {20: (data["y"], np.ones(data["n"], dtype=bool))},
        [20], design_leads=[20],
    )
    assert "station_offsets" not in model.to_json()["models"]["20"]


# ---------------------------------------------------------------------------
# Per-season recalibration
# ---------------------------------------------------------------------------


def test_a_season_with_enough_rows_gets_its_own_curve() -> None:
    rng = np.random.default_rng(9)
    n = pp.MIN_SEASON_ISOTONIC_ROWS * 3
    season = np.array(
        ["summer", "winter", "shoulder"] * pp.MIN_SEASON_ISOTONIC_ROWS, dtype="<U8",
    )
    score = rng.uniform(size=n)
    # Summer is over-confident and winter under-confident at the same score.
    rate = np.where(season == "summer", score * 0.5, np.minimum(score * 1.4, 1.0))
    y = (rng.uniform(size=n) < rate).astype(np.float64)
    pooled, curves = pp.fit_isotonic_by_season(score, y, season)
    assert set(curves) == {"summer", "winter", "shoulder"}
    at = 0.8
    assert float(curves["summer"].predict(np.array([at]))[0]) < float(
        pooled.predict(np.array([at]))[0]
    )
    assert float(curves["winter"].predict(np.array([at]))[0]) > float(
        pooled.predict(np.array([at]))[0]
    )


def test_a_thin_season_keeps_the_pooled_curve() -> None:
    rng = np.random.default_rng(10)
    n = pp.MIN_SEASON_ISOTONIC_ROWS + 100
    season = np.array(["summer"] * (n - 100) + ["winter"] * 100, dtype="<U8")
    score = rng.uniform(size=n)
    y = (rng.uniform(size=n) < score).astype(np.float64)
    _pooled, curves = pp.fit_isotonic_by_season(score, y, season)
    assert set(curves) == {"summer"}


def test_the_per_season_model_uses_the_row_s_own_curve() -> None:
    lead = pp.LeadModel(
        lead_min=20, intercept=0.0, coefficients=(1.0,),
        isotonic=IsotonicCalibrator((0.0, 1.0), (0.0, 1.0)),
        n=10, base_rate=0.1, converged=True, iterations=1,
        isotonic_by_season={
            "summer": IsotonicCalibrator((0.0, 1.0), (0.0, 0.2)),
        },
    )
    raw = np.array([1.0, 1.0])
    season = np.array(["summer", "winter"], dtype="<U8")
    assert lead.calibrate(raw, season).tolist() == pytest.approx([0.2, 1.0])
    # Without a season the pooled curve answers for every row.
    assert lead.calibrate(raw).tolist() == pytest.approx([1.0, 1.0])


# ---------------------------------------------------------------------------
# The onset-relevant (dry) subset
# ---------------------------------------------------------------------------


class _Grid:
    """A stand-in for ``decision_rows.GaugeGrid``, with its exact contract.

    ``outcome`` grades the slots whose END falls in ``(t, t + lead]`` and
    reports unusable where the window runs off the grid or a slot in it
    said nothing. Written out longhand here so ``dry_before`` is tested
    against the definition rather than against another copy of itself.
    """

    def __init__(self, wet: np.ndarray, known: np.ndarray, *, first_sec: int,
                 step_sec: int) -> None:
        self.wet, self.known = np.asarray(wet), np.asarray(known)
        self.first_sec, self.step_sec = int(first_sec), int(step_sec)
        self.n_slots = self.wet.shape[1]

    def outcome(self, t, station, lead_min):
        t = np.asarray(t, dtype=np.int64)
        station = np.asarray(station, dtype=np.int64)
        lo = (t - self.first_sec) // self.step_sec + 1
        hi = (t + int(lead_min) * 60 - self.first_sec) // self.step_sec
        out_wet = np.zeros(t.size, dtype=np.float64)
        usable = np.zeros(t.size, dtype=bool)
        for i in range(t.size):
            if lo[i] < 0 or hi[i] >= self.n_slots or hi[i] < lo[i]:
                continue
            window = slice(int(lo[i]), int(hi[i]) + 1)
            wet = bool(self.wet[station[i], window].any())
            all_known = bool(self.known[station[i], window].all())
            out_wet[i] = 1.0 if wet else 0.0
            usable[i] = wet or all_known
        return out_wet, usable


def _grid(rows: list[str]) -> _Grid:
    """``"..W..."`` per station: ``.`` dry+known, ``W`` wet, ``?`` unknown."""
    wet = np.array([[c == "W" for c in row] for row in rows])
    known = np.array([[c != "?" for c in row] for row in rows])
    return _Grid(wet, known, first_sec=600, step_sec=600)


def test_dry_before_looks_back_a_lagged_hour() -> None:
    """Six 10-minute slots, ending at the decision instant minus the lag."""
    # Slot k ends at 600 * (k + 1). The decision instant is at slot 11's
    # end (7200 s); with a 10 min lag the window is slots 5..10.
    grid = _grid([
        "..........." + "..",   # A: dry throughout
        "....W......" + "..",   # B: wet in slot 4, i.e. BEFORE the window
        ".........W." + "..",   # C: wet in slot 9, inside the window
        "......?...." + "..",   # D: one slot unknown inside the window
    ])
    t = np.full(4, 7200, dtype=np.int64)
    station = np.arange(4, dtype=np.int64)
    out = pp.dry_before(grid, t, station, minutes=60, lag_min=10.0)
    assert out[0] == 1.0          # dry for the whole hour
    assert out[1] == 1.0          # the wet slot is older than the window
    assert out[2] == 0.0          # wet inside the window
    assert math.isnan(out[3])     # a silent gauge certifies nothing


def test_dry_before_off_the_edge_of_the_archive_is_unknown() -> None:
    grid = _grid(["......"])
    out = pp.dry_before(
        grid, np.array([600], dtype=np.int64), np.array([0]), lag_min=0.0,
    )
    assert math.isnan(out[0])


def test_the_subset_prefers_the_stored_column() -> None:
    """The writer had the slots; the archive may since have been trimmed."""
    rows = {
        "raw_frac_20": np.array([0.1, 0.2, 0.3]),
        pp.DRY_COLUMN: np.array([1.0, 0.0, np.nan]),
    }
    assert pp.dry_subset(rows).tolist() == [True, False, False]


def test_the_subset_falls_back_to_the_grid_where_the_column_is_null() -> None:
    grid = _grid(["............", "........W..."])
    rows = {
        "raw_frac_20": np.array([0.1, 0.2]),
        pp.DRY_COLUMN: np.array([0.0, np.nan]),
    }
    out = pp.dry_subset(
        rows, grid=grid,
        t=np.array([7200, 7200], dtype=np.int64),
        station=np.array([0, 1], dtype=np.int64),
        lag_min=10.0,
    )
    # Row 0 keeps its stored 0; row 1 is derived, and its gauge was wet.
    assert out.tolist() == [False, False]


def test_rows_with_no_column_and_no_grid_are_simply_not_in_the_subset() -> None:
    rows = {"raw_frac_20": np.array([0.1, 0.2])}
    assert pp.dry_subset(rows).tolist() == [False, False]


# ---------------------------------------------------------------------------
# Feature families
# ---------------------------------------------------------------------------


def test_every_v2_design_column_belongs_to_a_family() -> None:
    """An unfiled column would be silently immune to the ablation."""
    spec = pp.design_spec(None, (10, 20, 30, 45, 60), version=pp.DESIGN_V2)
    names = pp.design_columns((10, 20, 30, 45, 60), spec)
    unfiled = [name for name in names if pp.feature_family(name) == "other"]
    assert unfiled == []


def test_an_interaction_is_dropped_with_either_parent() -> None:
    names = ("up_no_echo", "bulk_kmh", "up_no_echo_x_bulk_kmh", "hour_sin")
    assert pp.family_columns(names, "up").tolist() == [True, False, True, False]
    assert pp.family_columns(names, "motion").tolist() == [
        False, True, True, False,
    ]


def test_a_spline_column_inherits_its_base_columns_family() -> None:
    assert pp.feature_family("bulk_kmh_ns1") == "motion"
    assert pp.feature_family("log1p_up_dist_km_ns2") == "up"
    assert pp.feature_family("raw_frac_45_ns3") == "raw_frac"


# ---------------------------------------------------------------------------
# The evaluation protocol
# ---------------------------------------------------------------------------


@pytest.fixture(scope="module")
def synthetic() -> dict:
    """The golden rows, plus the fold keys and the curve baseline.

    The baseline is generous on purpose: the isotonic curve is fitted IN
    SAMPLE on the very rows it is then scored on, so any win against it
    is a win against the best a fraction-only calibration could manage.
    """
    from dmi_nowcast_core.calibrate import fit_isotonic

    golden = _golden_features()
    fraction = golden["features"][pp.raw_fraction_column(LEADS[0])]
    return {
        **golden,
        "month": pp.year_months_from_epoch(golden["t"]),
        "day": golden["t"] // 86_400,
        "baseline": {
            lead: np.asarray(
                fit_isotonic(fraction, golden["truth"][lead][0]).predict(fraction),
                dtype=np.float64,
            )
            for lead in LEADS
        },
    }


def test_the_baseline_can_itself_be_a_refitted_model(synthetic: dict) -> None:
    """``--baseline refit-v1``: both arms fitted in the same folds.

    The point is that the baseline is out of fold too. A v1 model scored
    in sample against a v2 model scored out of fold would be a comparison
    of two different protocols dressed up as a comparison of two designs.
    """
    result = pp.leave_one_month_out(
        synthetic["features"], synthetic["truth"], list(LEADS),
        month=synthetic["month"], day=synthetic["day"],
        baseline=synthetic["baseline"],
        settings=pp.FitSettings(design=pp.DESIGN_V2),
        baseline_settings=pp.FitSettings(design=pp.DESIGN_V1),
        baseline_label="refit-v1", n_resamples=0,
    )
    assert result["settings"]["baseline"] == "refit-v1"
    assert result["settings"]["baseline_fit"]["design"] == pp.DESIGN_V1
    assert result["settings"]["fit"]["design"] == pp.DESIGN_V2
    held = result["baseline_out_of_fold"]
    assert set(held) == set(LEADS)
    # A refitted baseline is a model's out-of-fold prediction, so it is
    # NOT the served curve it replaced.
    assert not np.allclose(
        held[20], np.asarray(synthetic["baseline"][20]), atol=1e-6,
    )


def test_the_dry_stratum_is_reported_beside_the_seasons(synthetic: dict) -> None:
    features = dict(synthetic["features"])
    dry = np.zeros(synthetic["n"], dtype=np.float64)
    dry[::2] = 1.0
    features[pp.DRY_COLUMN] = dry
    result = pp.leave_one_month_out(
        features, synthetic["truth"], list(LEADS),
        month=synthetic["month"], day=synthetic["day"],
        baseline=synthetic["baseline"], n_resamples=0,
    )
    block = result["leads"]["20"][pp.DRY]
    assert block["n"] > 0
    assert block["n"] < result["leads"]["20"][pp.POOLED]["n"]
    assert "bss" in block["baseline"] and "bss" in block["postprocess"]


def test_the_learning_curve_has_one_row_per_budget(synthetic: dict) -> None:
    rows = pp.learning_curve(
        synthetic["features"], synthetic["truth"], list(LEADS),
        month=synthetic["month"], day=synthetic["day"],
        settings=pp.FitSettings(), days=[4, 12],
    )
    assert [row["days"] for row in rows] == [4, 12]
    for row in rows:
        assert set(row["leads"]) == {str(lead) for lead in LEADS}
        assert row["leads"]["20"][pp.POOLED]["n"] > 0
        assert math.isfinite(row["leads"]["20"][pp.POOLED]["bss"])
    # More days of archive means more training rows, which is the only
    # monotone claim this fixture is big enough to make.
    assert rows[1]["train_rows"] > rows[0]["train_rows"]


def test_the_ablation_reports_a_delta_per_family(synthetic: dict) -> None:
    result = pp.ablation(
        synthetic["features"], synthetic["truth"], list(LEADS),
        month=synthetic["month"],
        settings=pp.FitSettings(design=pp.DESIGN_V2),
        families=["raw_frac", "up", "time"],
    )
    assert [entry["family"] for entry in result["dropped"]] == [
        "raw_frac", "up", "time",
    ]
    for entry in result["dropped"]:
        assert entry["columns"] > 0
        assert math.isfinite(entry["leads"]["20"][pp.POOLED]["delta"])
    # The fixture's outcome is driven by the upstream block, so taking it
    # away has to hurt more than taking the clock away.
    up = result["dropped"][1]["leads"]["20"][pp.POOLED]["delta"]
    time_family = result["dropped"][2]["leads"]["20"][pp.POOLED]["delta"]
    assert up < time_family


def test_an_unknown_family_or_mode_is_refused() -> None:
    with pytest.raises(ValueError, match="famil"):
        pp.FitSettings(drop_families=("nonsense",)).validate()
    with pytest.raises(ValueError, match="model kind"):
        pp.FitSettings(kind="forest").validate()
    with pytest.raises(ValueError, match="design version"):
        pp.FitSettings(design="v3").validate()
    with pytest.raises(ValueError, match="isotonic mode"):
        pp.FitSettings(isotonic="loess").validate()


# ---------------------------------------------------------------------------
# One model across leads, and the ordering it must respect
# ---------------------------------------------------------------------------


def test_the_four_kinds_are_named_once(  ) -> None:
    assert pp.MODEL_KINDS == (
        "logistic", "logistic-shared", "trees", "trees-shared",
    )
    assert pp.is_shared_kind("logistic-shared")
    assert pp.is_shared_kind("trees-shared")
    assert not pp.is_shared_kind("trees")
    assert pp.is_tree_kind("trees-shared")
    assert not pp.is_tree_kind("logistic-shared")
    assert pp.FitSettings(kind="logistic-shared").shared_lead is True
    assert pp.FitSettings().shared_lead is False


def test_a_shared_design_collapses_the_per_lead_columns() -> None:
    """``raw_frac_own`` is the fraction at the horizon being asked about."""
    spec = pp.design_spec(None, (20, 30), version=pp.DESIGN_V1, shared_lead=True)
    assert [name for name, _sources in spec.own_columns] == ["raw_frac_own"]
    sources = dict(dict(spec.own_columns)["raw_frac_own"])
    assert sources == {20: "raw_frac_20", 30: "raw_frac_30"}
    names = pp.design_columns((20, 30), spec)
    assert names[-3:] == ("raw_frac_own", "lead_min", "log_lead_min")


def test_the_shared_columns_are_filled_from_the_lead_being_predicted() -> None:
    """And by the SAME code at fit time and at serving time."""
    spec = pp.design_spec(None, (20, 30), version=pp.DESIGN_V1, shared_lead=True)
    names = pp.design_columns((20, 30), spec)
    rows = _one_row()
    design = pp.build_design(rows, (20, 30), spec)
    index = {name: i for i, name in enumerate(names)}
    # Before filling, the shared tail is missing, not zero.
    assert math.isnan(design[0, index["raw_frac_own"]])
    pp.fill_shared_columns(design, 30, names, spec)
    assert design[0, index["raw_frac_own"]] == design[0, index["raw_frac_30"]]
    assert design[0, index["lead_min"]] == 30.0
    assert design[0, index["log_lead_min"]] == pytest.approx(math.log(30.0))
    pp.fill_shared_columns(design, 20, names, spec)
    assert design[0, index["raw_frac_own"]] == design[0, index["raw_frac_20"]]


def _shared_fixture(seed: int = 21) -> dict:
    """Rows at four leads whose outcome rises with the lead and the fraction."""
    rng = np.random.default_rng(seed)
    n = 6000
    t = (
        np.datetime64("2026-01-01T06:00:00").astype("datetime64[s]").astype(np.int64)
        + np.arange(n) * 600
    )
    fraction = rng.uniform(size=n)
    leads = (20, 30, 45, 60)
    features = {
        "season": pp.seasons_from_epoch(t),
        "hour_utc": pp.hours_from_epoch(t).astype(np.float64),
        "up_dist_km": rng.uniform(0.0, 40.0, size=n),
        "bulk_kmh": rng.uniform(5.0, 60.0, size=n),
    }
    truth: dict[int, tuple[np.ndarray, np.ndarray]] = {}
    for lead in leads:
        # The fraction at lead L is the same signal scaled by the horizon —
        # so a shared fit has something real to learn about the lead.
        features[pp.raw_fraction_column(lead)] = np.clip(
            fraction * (lead / 60.0), 0.0, 1.0,
        )
        logit = -2.0 + 3.0 * fraction + 0.03 * lead
        y = (rng.uniform(size=n) < 1 / (1 + np.exp(-logit))).astype(np.float64)
        truth[lead] = (y, np.ones(n, dtype=bool))
    return {
        "features": features, "truth": truth, "leads": list(leads),
        "month": pp.year_months_from_epoch(t), "day": t // 86_400, "n": n,
    }


def test_a_shared_logistic_gives_every_lead_one_coefficient_vector() -> None:
    """Shared slopes, shared offsets — only the recalibration is per lead."""
    data = _shared_fixture()
    model = pp.fit_postprocess(
        data["features"], data["truth"], data["leads"],
        design_leads=data["leads"],
        settings=pp.FitSettings(kind=pp.KIND_LOGISTIC_SHARED),
    )
    assert model.kind == pp.KIND_LOGISTIC_SHARED
    assert model.is_shared
    first = model.models[data["leads"][0]].coefficients
    for lead in data["leads"][1:]:
        assert model.models[lead].coefficients == first
    # The isotonic curves are NOT shared: the base rate is not.
    curves = {
        lead: model.models[lead].isotonic.calibrated_values
        for lead in data["leads"]
    }
    assert curves[20] != curves[60]
    # Every lead's fit stands on its own rows, and the shared fit on all.
    assert model.models[20].message == "shared across leads"


def test_a_shared_logistic_learns_that_a_longer_lead_is_likelier() -> None:
    data = _shared_fixture()
    model = pp.fit_postprocess(
        data["features"], data["truth"], data["leads"],
        design_leads=data["leads"],
        settings=pp.FitSettings(kind=pp.KIND_LOGISTIC_SHARED),
    )
    predicted = model.predict(data["features"])
    means = [float(np.mean(predicted[lead])) for lead in data["leads"]]
    assert means == sorted(means)


class TestTheLeadOrdering:
    """P(rain within 60) >= P(rain within 45): the 60 window contains it.

    The running max is the same guard ``national.enforce_lead_monotonic``
    puts on the served ``p_rain`` — reused, not restated — because the
    per-lead isotonic curves here are as free to cross as the national
    curves were.
    """

    def _model(self, kind: str):
        data = _shared_fixture(seed=33)
        model = pp.fit_postprocess(
            data["features"], data["truth"], data["leads"],
            design_leads=data["leads"], settings=pp.FitSettings(kind=kind),
        )
        return model, data

    def test_a_shared_model_never_returns_p45_below_p30(self) -> None:
        model, data = self._model(pp.KIND_LOGISTIC_SHARED)
        predicted = model.predict(data["features"])
        assert np.all(predicted[45] >= predicted[30] - 1e-12)
        assert np.all(predicted[60] >= predicted[45] - 1e-12)
        assert np.all(predicted[30] >= predicted[20] - 1e-12)

    def test_the_per_lead_model_gets_the_same_safety_net(self) -> None:
        model, data = self._model(pp.KIND_LOGISTIC)
        predicted = model.predict(data["features"])
        for shorter, longer in zip(data["leads"], data["leads"][1:]):
            assert np.all(predicted[longer] >= predicted[shorter] - 1e-12)

    def test_asking_for_one_lead_gives_the_same_number_as_asking_for_all(
        self,
    ) -> None:
        """Otherwise the guard would depend on how the caller asked."""
        model, data = self._model(pp.KIND_LOGISTIC)
        every = model.predict(data["features"])
        for lead in data["leads"]:
            assert model.predict(data["features"], lead) == pytest.approx(
                every[lead], abs=0.0,
            )

    def test_a_crossing_pair_of_curves_is_repaired_not_served(self) -> None:
        """The mechanism, on a model built to violate the ordering."""
        crossing = {
            20: np.array([0.9, 0.1]),
            30: np.array([0.2, 0.4]),
            45: np.array([np.nan, 0.3]),
        }
        fixed = pp.enforce_lead_monotonic(crossing)
        assert fixed[20].tolist() == [0.9, 0.1]
        assert fixed[30].tolist() == [0.9, 0.4]
        # A NaN stays a NaN — "the model could not speak for this row" is
        # not a probability to run a maximum over.
        assert math.isnan(fixed[45][0])
        assert fixed[45][1] == 0.4


def test_the_out_of_fold_predictions_are_monotone_too() -> None:
    """The evaluation has to score the number the service would serve."""
    data = _shared_fixture(seed=44)
    held = pp.out_of_fold_predictions(
        data["features"], data["truth"], data["leads"],
        month=data["month"], settings=pp.FitSettings(kind=pp.KIND_LOGISTIC_SHARED),
        design_leads=data["leads"],
    )["out_of_fold"]
    for shorter, longer in zip(data["leads"], data["leads"][1:]):
        finite = np.isfinite(held[shorter]) & np.isfinite(held[longer])
        assert np.all(held[longer][finite] >= held[shorter][finite] - 1e-12)


def test_a_shared_logistic_round_trips_through_json() -> None:
    data = _shared_fixture(seed=55)
    model = pp.fit_postprocess(
        data["features"], data["truth"], data["leads"],
        design_leads=data["leads"],
        settings=pp.FitSettings(kind=pp.KIND_LOGISTIC_SHARED),
    )
    payload = json.loads(model.dumps())
    assert payload["kind"] == "logistic-shared"
    assert payload["design"]["lead_column"] == "lead_min"
    assert payload["design"]["own_columns"][0]["column"] == "raw_frac_own"
    restored = pp.PostprocessModel.loads(model.dumps())
    for lead in data["leads"]:
        assert restored.predict(data["features"], lead) == pytest.approx(
            model.predict(data["features"], lead), abs=1e-12,
        )


def test_the_lead_columns_carry_a_monotone_constraint_for_the_trees() -> None:
    """+1 on the lead, 0 on everything else — LightGBM's own encoding."""
    names = ("raw_frac_own", "bulk_kmh", "lead_min", "log_lead_min")
    assert pp._lead_monotone_constraints(names) == [0, 0, 1, 1]
